Bug fix for new asset creation with same site reference number
civicledger/aud-api pull request #19
Opened 2022-03-24 02:55 UTC by Farhad-Rezwan

2022-03-24 02:57 UTC, Farhad-Rezwan commented on app/Controllers/Http/EntriesController.ts
> -    const assetEntries = ledger.entries.filter(entry => entry.name === 'NewAsset');
I have moved these code below the entries enforcer check. Because it should check policy after the validation is successful.

2022-03-24 02:57 UTC, Farhad-Rezwan commented on app/Services/GuardianService.ts
> +      await axiosInstance.put(`profiles/${user.username}`, profile);
The current guardian changes enforce the new url change.

2022-03-24 06:27 UTC, smallbatch-apps requested changes

2022-03-24 06:27 UTC, smallbatch-apps commented on app/Repositories/AssetLucidRepository.ts
> +        .status(StatusCodes.UnprocessableEntity)
This should actually be a `409 Conflict`. The 422 used here means that the request sent some sort of data that wasn't actionable. 409 Conflict means that it was actionable, but would have conflicted with an existing entity.

2022-03-24 07:02 UTC, Farhad-Rezwan commented on app/Repositories/AssetLucidRepository.ts
> +        .status(StatusCodes.UnprocessableEntity)
resolved

2022-03-24 08:33 UTC, thanapat-civicledger commented on app/Controllers/Http/EntriesController.ts
> +    const assetEntry = await EntryLucidRepository.getAssetEntry(assetEntries, event);
It may be slightly better to move this EntryLucidRepository.getAssetEntry() to be inside the if() block (Line: 65). It will save a bit of computation time. :)

2022-03-24 22:31 UTC, Farhad-Rezwan commented on app/Controllers/Http/EntriesController.ts
> +    const assetEntry = await EntryLucidRepository.getAssetEntry(assetEntries, event);
agree

2022-03-24 23:05 UTC, Farhad-Rezwan commented on app/Services/GuardianService.ts
> +      const policy = policies.find(({ name }) => name.includes(policyName));
policies sometimes imported as `CriticalMineralsPolicy_19828112`

2022-03-25 06:26 UTC, smallbatch-apps requested changes

2022-03-25 07:27 UTC, Farhad-Rezwan commented on app/Controllers/Http/EntriesController.ts
> +    }
Yup agree,

2022-03-25 07:34 UTC, Farhad-Rezwan commented on app/Controllers/Http/EntriesController.ts
> +    }
resolved

2022-03-25 07:34 UTC, Farhad-Rezwan commented on app/Repositories/AssetLucidRepository.ts
> +      return ctx?.response.status(StatusCodes.Conflict).send({ error: `Asset with same ${primaryIdName} already exists: ${primaryIdValue}` });
resolved

2022-03-25 07:45 UTC, merged