CM - 97 Swagger error messages
civicledger/aud-api pull request #26
Opened 2022-04-01 05:52 UTC by Farhad-Rezwan

![Screen Shot 2022-04-01 at 4 52 02 pm](https://user-images.githubusercontent.com/53939630/161203170-a195e3b6-bc3e-4ef0-aad0-4b2a23c30f2a.png)

2022-04-04 03:18 UTC, smallbatch-apps requested changes

2022-04-04 03:18 UTC, smallbatch-apps commented on app/Controllers/Http/AssetsController.ts
> +      throw new ForbiddenException('No permission to access asset ledger', StatusCodes.Forbidden);
As above it's important to note that this is the response that goes back to the user. You're essentially saying that they're forbidden from accessing this resource. Why? They should have permission for this resource, it's their resource. Internally something is invalid, but the user doesn't know that. Essentially this needs to be some kind of `5xx` error.

2022-04-04 03:18 UTC, smallbatch-apps commented on docs/swagger/assets.yml
> +              $ref: '#/components/errors/UnauthorizedAccess'
It's interesting that this is able to access errors from an external file. If that's how it's done maybe we can do the same with schemas as well?

2022-04-04 03:31 UTC, Farhad-Rezwan commented on app/Controllers/Http/AssetsController.ts
> +      throw new ForbiddenException('No permission to access asset ledger', StatusCodes.Forbidden);
Makes sense

2022-04-04 03:32 UTC, Farhad-Rezwan commented on docs/swagger/assets.yml
> +              $ref: '#/components/errors/UnauthorizedAccess'
Yup.

2022-04-04 03:49 UTC, Farhad-Rezwan commented on app/Controllers/Http/AssetsController.ts
> +      throw new LedgerNotFoundException('No Parent Ledger for company', StatusCodes.NotFound);
Makes sense

2022-04-04 03:51 UTC, Farhad-Rezwan commented on app/Controllers/Http/AssetsController.ts
> +      throw new UnauthorizedAccessException('Unauthorized access', StatusCodes.UnauthorizedAccess);
done

2022-04-06 08:18 UTC, thanapat-civicledger commented on docs/swagger/assets.yml
> +        description: Company not found for user
This is a bit confusing for me, as the same error code will be returned if no asset is found for the given asset id.
I don't know how to better handle this case. Maybe use the description as "Asset not found | Company not found for user"?

2022-04-06 19:18 UTC, smallbatch-apps commented on app/Controllers/Http/AssetsController.ts
> +    if (!user || user.companyId !== jwtAccount.companyId)
Sorry, I missed this one, can you wrap it too? This sort of multiple line conditional is very error prone. It should be in brackets.

2022-04-07 02:16 UTC, Farhad-Rezwan commented on app/Controllers/Http/AssetsController.ts
> +    if (!user || user.companyId !== jwtAccount.companyId)
Oops sorry I missed it to.

2022-04-07 02:16 UTC, Farhad-Rezwan commented on app/Controllers/Http/AssetsController.ts
> +    if (!user || user.companyId !== jwtAccount.companyId)
Just updated

2022-04-07 02:20 UTC, Farhad-Rezwan commented on docs/swagger/assets.yml
> +        description: Company not found for user
Yes, we can do that. This doc is just an example of one use case error, however I have updated accordingly.

2022-04-07 03:16 UTC, thanapat-civicledger approved these changes
Looks good to me

2022-04-07 14:35 UTC, smallbatch-apps approved these changes

2022-04-07 14:36 UTC, merged