CM-101 initial endpoint to return document of transactions for an asset
civicledger/aud-api pull request #29
Opened 2022-04-08 07:15 UTC by thanapat-civicledger

2022-04-08 11:13 UTC, smallbatch-apps requested changes

2022-04-08 11:13 UTC, smallbatch-apps commented on start/routes.ts
> +  Route.get('assets/:id/transactions', 'AssetsController.transactions');
Don't make up method names, use the existing ones - this would be an index.

2022-04-08 11:13 UTC, smallbatch-apps commented on app/Services/HashgraphService.ts
> +    const transactionUrl = Env.get('HASHGRAPH_TRANSACTION_URL', 'https://app.dragonglass.me/transactions');
If you're doing this there's no reason to make it an environment variable. In fact I'd say just... don't. Unless you need to change it for a different network, in which case why set the default value?

2022-04-08 11:13 UTC, smallbatch-apps commented on app/Controllers/Http/AssetsController.ts
> +  public async transactions({ request, jwtAccount, ...args }: HttpContextContract) {
Make a new controller for this, instead of just adding a new method. It's not a restful method otherwise. Also, I'm not sure why you want `...args`. These aren't arguments, they're properties of the `HttpContextContract` object, which includes things like `bouncer`, `auth` and `params`. You really don't want to do that.

2022-04-08 11:13 UTC, smallbatch-apps commented on app/Controllers/Http/AssetsController.ts
> +    const { asset } = await this.show({ request, jwtAccount, ...args });
I don't know what this is intended to do, but you really don't want to be calling a controller method from another one.

2022-04-08 11:13 UTC, smallbatch-apps commented on app/Controllers/Http/AssetsController.ts
> +        ?.event.primaryIdName;
This isn't right, but it's a little hard to read through, so we'll talk through it on Monday.

2022-04-11 02:21 UTC, thanapat-civicledger commented
@smallbatch-apps 
I have made changes to this PR. It would be great if we can walk through it together.

2022-04-11 03:24 UTC, Farhad-Rezwan commented on app/Controllers/Http/TransactionsController.ts
> +    // List all transactions for this asset
Please remove the comments in production

2022-04-11 04:09 UTC, thanapat-civicledger commented on app/Controllers/Http/TransactionsController.ts
> +    // List all transactions for this asset
Removed

2022-04-21 02:34 UTC, Farhad-Rezwan reviewed
please pull main, the pattern of using repositories are changed.

2022-04-21 04:23 UTC, thanapat-civicledger commented
> please pull main, the pattern of using repositories are changed.

Done

2022-04-21 19:08 UTC, smallbatch-apps approved these changes

2022-04-21 19:08 UTC, merged