CM-103 Credential management endpoint duration
civicledger/aud-api pull request #33
Opened 2022-04-13 07:28 UTC by thanapat-civicledger

2022-04-18 07:50 UTC, thanapat-civicledger commented on app/Controllers/Http/CompliancesController.ts
> +    const credentialSubject = profile.vcDocument.document.credentialSubject;
The new guardian build has this structure change. I have added the subfield .document to the path.

2022-04-18 07:50 UTC, thanapat-civicledger commented on app/Controllers/Http/CompliancesController.ts
> +    const licences = await Promise.all(
The previous version of this code did not work as expected. It returned the array of promises which cannot be rendered to JSON correctly. I have added Promise.all to collect the result into an array before moving to the next step.

2022-04-18 07:50 UTC, thanapat-civicledger commented on app/Repositories/CredentialLucidRepository.ts
> +      compliant: event.duration === 12 && event.duration === eventDuration,
I am not sure if there is anywhere else that we need to make the change. Please let me know if I missed something .

2022-04-20 05:59 UTC, thanapat-civicledger commented on app/Repositories/CredentialLucidRepository.ts
> +                      { name: 'NonCompliantEvent', event: { nonCompliantEventName: name, nonComplianceReason: 'Invalid duration', nonCompliantEvent: entryEvent } };
Thanks. I have made changes to that.

2022-04-20 10:07 UTC, thanapat-civicledger commented
@Farhad-Rezwan I have made changes per your comments and also skip the creation of VC in case of a non-compliant event. Could you please review the code again?

2022-04-21 02:15 UTC, Farhad-Rezwan commented on app/Repositories/CredentialLucidRepository.ts
> +    const isCompliant = event.duration === 12 && event.duration === eventDuration;
event.duration can be optional.

2022-04-21 02:15 UTC, Farhad-Rezwan commented on app/Repositories/CredentialLucidRepository.ts
> +    const isCompliant = event.duration === 12 && event.duration === eventDuration;
event.duration can be optional.

2022-04-21 02:18 UTC, Farhad-Rezwan reviewed
looks good, However, the duration can be optional if you see the seeder, please consider that. 

in seeder you can see:
```
{ name: 'validFrom', label: 'Validity Start Date and Time', type: FieldTypes.DateTime, rules },
{ name: 'duration', label: 'Licence Duration in Month', type: FieldTypes.Number },
```
and in the same file, `rules` means required.
`const rules = [{ type: RuleTypes.Required }];`

2022-04-21 03:51 UTC, thanapat-civicledger commented on app/Repositories/CredentialLucidRepository.ts
> +    const isCompliant = event.duration === 12 && event.duration === eventDuration;
@Farhad-Rezwan 
I have made changes so that we will only check the validFrom and validTo if the duration was not sent.

2022-04-21 06:26 UTC, Farhad-Rezwan approved these changes
Looks good now

2022-04-22 02:57 UTC, smallbatch-apps requested changes

2022-04-22 02:57 UTC, smallbatch-apps commented on app/Repositories/CredentialLucidRepository.ts
> +    }
Hey Thanapat! I misunderstood this code at first and thought it had more to do with the credentials than it actually does. It can actually be quite a bit simpler.

2022-04-22 04:56 UTC, Farhad-Rezwan commented on database/seeders/CriticalMinerals.ts
> +      { name: 'duration', label: 'Licence Duration in Month', type: FieldTypes.Number, rules },
Hello @thanapat-civicledger I missed this part before approving. The duration is actually optional. They might not send us the duration. Which means you can remove the rules.
source: https://civicledger.atlassian.net/browse/CM-92?jql=text%20~%20%22Data%20Amend%22%20order%20by%20created%20DESC

2022-04-22 05:05 UTC, Farhad-Rezwan requested changes

2022-04-22 05:05 UTC, Farhad-Rezwan commented on database/seeders/CriticalMinerals.ts
> +      { name: 'duration', label: 'Licence Duration in Month', type: FieldTypes.Number, rules },
We can make it optional and set the default value to 12. What is your opinion on this @smallbatch-apps.

2022-04-22 05:10 UTC, Farhad-Rezwan approved these changes

2022-04-23 13:49 UTC, thanapat-civicledger commented
@smallbatch-apps I have refactored the code per our discussion. Please review and let me know if there are any changes needed.

2022-04-25 20:29 UTC, merged