Feature/cm 80 enforce account balance policy
civicledger/aud-api pull request #34
Opened 2022-04-20 02:08 UTC by Farhad-Rezwan

2022-04-20 10:20 UTC, thanapat-civicledger commented on app/Services/GuardianService.ts
> +export type ComplianceStatus = {
This is great. I will use type in CM-103 too.

2022-04-21 08:33 UTC, thanapat-civicledger commented on app/Services/GuardianService.ts
> +  hashgraphService: HashgraphService;
Should these properties be private?

2022-04-22 03:56 UTC, smallbatch-apps requested changes

2022-04-22 03:56 UTC, smallbatch-apps commented on app/Repositories/EntryLucidRepository.ts
> +      complianceStatus = await this.guardianService.checkBalancePolicy(ledger, credential, primaryId, entryDetails);
What is the purpose of setting complianceStatus above? If the `checkBalancePolicy` replaces it, why set it in the first place?

2022-04-22 03:56 UTC, smallbatch-apps commented on app/Services/GuardianService.ts
> +  hashgraphService: HashgraphService;
Valid

2022-04-22 04:20 UTC, Farhad-Rezwan commented on app/Repositories/EntryLucidRepository.ts
> +      complianceStatus = await this.guardianService.checkBalancePolicy(ledger, credential, primaryId, entryDetails);
Makes sense. we should not need that because we are not checking anything before doing setting the `balanceCheckPolicy`

2022-04-22 04:38 UTC, Farhad-Rezwan commented on app/Repositories/EntryLucidRepository.ts
> +      complianceStatus = await this.guardianService.checkBalancePolicy(ledger, credential, primaryId, entryDetails);
Resolved

2022-04-22 08:53 UTC, smallbatch-apps requested changes

2022-04-22 08:53 UTC, smallbatch-apps commented on app/Services/GuardianService.ts
> +    if (isNaN(allocationUsed as any)) throw new GuardianException('token balance not found', StatusCodes.InternalServerError);
Wrap this in brackets, it's way too long for this. I'm also not that fan of this conditional, especially the `as any`. It seems like a really complex way to check for... false. Also, is there any reason to throw an exception here? A balance of 0 is perfectly valid.

2022-04-25 03:12 UTC, Farhad-Rezwan commented on app/Services/GuardianService.ts
> +    if (isNaN(allocationUsed as any)) throw new GuardianException('token balance not found', StatusCodes.InternalServerError);
Resolved

2022-04-25 03:26 UTC, Farhad-Rezwan commented on app/Services/GuardianService.ts
> +    if (allocationUsed === undefined) {
`getTokenBalance` either returns - `allocation value`, `zero` or undefined. I am throwing if the allocation used is only  undefined. Yes, both zero and any allocation value is valid to pass through the calculation.

2022-04-25 20:30 UTC, smallbatch-apps approved these changes

2022-04-25 20:30 UTC, merged