Feature/cm 116 get post compliance data end points
civicledger/aud-api pull request #39
Opened 2022-05-12 22:40 UTC by smallbatch-apps

2022-05-13 04:04 UTC, Farhad-Rezwan requested changes

2022-05-13 04:04 UTC, Farhad-Rezwan commented on app/Repositories/EntryLucidRepository.ts
> +    this.everledgerService.sendComplianceUpdate(entry);
should we `await` here the method `sendComplianceUpdate` is an async function.

2022-05-13 04:07 UTC, thanapat-civicledger commented on app/Services/EverledgerService.ts
> +  async sendComplianceUpdate(entry: Entry) {
maybe a bit better to type hint the return type as `Promise<void>` here

2022-05-13 04:11 UTC, Farhad-Rezwan commented on app/Repositories/EntryLucidRepository.ts
> +    this.everledgerService.sendComplianceUpdate(entry);
agree we might not wait for the update to be sent.

2022-05-13 04:22 UTC, Farhad-Rezwan requested changes

2022-05-13 04:22 UTC, Farhad-Rezwan commented on app/Services/EverledgerService.ts
> +      const allocationUsed = await this.hashgraphService.getTokenBalance(profile.hederaAccountId, token.id);
this actually be `token.tokenId` 
here the tokenId represents consensus service token id

2022-05-13 04:24 UTC, Farhad-Rezwan commented on app/Services/EverledgerService.ts
> +      const allocationRemaining = +allocation - +allocationUsed;
FYI, this `allocationRemaining` could sometimes be negative values like -17 ML. I think it is not much an issue, what is your opinion?

2022-05-16 03:12 UTC, smallbatch-apps commented on app/Services/EverledgerService.ts
> +      const allocationRemaining = +allocation - +allocationUsed;
Yeah, that's fine

2022-05-16 03:14 UTC, smallbatch-apps commented on app/Services/EverledgerService.ts
> +      const allocationUsed = await this.hashgraphService.getTokenBalance(profile.hederaAccountId, token.id);
Oh you're probably right. I'll fix that.

2022-05-16 10:24 UTC, thanapat-civicledger commented on app/Repositories/LedgerLucidRepository.ts
> +      return entry.event[entry.event.primaryIdName] === event.primaryIdValue;
@smallbatch-apps 
Should we make change to the POST /credentials endpoint to require this primaryIdValue field?
Right now, that endpoint does not require this field. It will return "Ledger not found for asset" exception if we call the endpoint without this primaryIdValue field.

2022-05-16 23:33 UTC, Farhad-Rezwan commented on app/Services/EverledgerService.ts
> +        compliant: true
wondering if this be false sometimes? or, is it out of scope for this story at the moment?

2022-05-16 23:34 UTC, Farhad-Rezwan approved these changes
I just got one question, regarding `compliance: true`, please refer the comment. Other than that everything looks fine. I have approved

2022-05-17 03:07 UTC, smallbatch-apps commented on app/Services/EverledgerService.ts
> +        compliant: true
I just needed it done, quite frankly

2022-05-19 10:22 UTC, merged