CM - 70 Integrate policy integration
civicledger/aud-api pull request #5
Opened 2022-03-03 05:06 UTC by Farhad-Rezwan

2022-03-08 02:15 UTC, Farhad-Rezwan commented on app/Controllers/Http/AssetsController.ts
> -    const { tokenId } = await this.guardianService.createToken(assetName, Object(otherEventValues)[primaryIdName]);
We are not creating a token for asset, the token will be created by the seeder so we don't need to save token information. Also token association is not required, tokens will already be associated with the `root user`/ `for an asset`

2022-03-08 16:21 UTC, smallbatch-apps requested changes

2022-03-09 02:51 UTC, Farhad-Rezwan commented on app/Services/GuardianService.ts
> +      ref: null,
Agree it is not required to make successful request.

2022-03-10 00:46 UTC, smallbatch-apps approved these changes

2022-03-10 01:42 UTC, merged

2022-03-10 01:43 UTC, Farhad-Rezwan commented on app/Controllers/Http/EntriesController.ts
>        .firstOrFail();
I have resolved that.