Cm 84 enable asset and licence creation in seeder
civicledger/aud-api pull request #8
Opened 2022-03-10 05:06 UTC by Farhad-Rezwan

2022-03-11 04:35 UTC, smallbatch-apps requested changes

2022-03-11 04:35 UTC, smallbatch-apps commented on app/Controllers/Http/CredentialsController.ts
> +    const assetEntry = await EntryLucidRepository.getAssetEntry(company.entries, request.input('event'));
I'm a little worried about this because you're actually doing a search for all entries, not just the entries on the Parent Ledger, which this should be searching.

2022-03-11 04:35 UTC, smallbatch-apps commented on app/Repositories/AssetLucidRepository.ts
> +        policyId: Env.get('CM_POLICY_ID'),
We're changing this in a different story, right?

2022-03-11 04:35 UTC, smallbatch-apps commented on database/seeders/CriticalMinerals.ts
> +import CredentialLucidRepository from 'App/Repositories/CredentialLucidRepository';
This should be imported above

2022-03-11 04:35 UTC, smallbatch-apps commented on database/seeders/CriticalMinerals.ts
> +    const cmDischargeLicenceId = 'ee522a75-0873-4260-8f4f-85b2f387b543';
Why are we hardcoding the licence ids?

2022-03-11 05:04 UTC, Farhad-Rezwan commented on app/Repositories/AssetLucidRepository.ts
> +        policyId: Env.get('CM_POLICY_ID'),
yup

2022-03-11 05:04 UTC, Farhad-Rezwan commented on database/seeders/CriticalMinerals.ts
> +import CredentialLucidRepository from 'App/Repositories/CredentialLucidRepository';
yup missed it

2022-03-11 05:09 UTC, Farhad-Rezwan commented on database/seeders/CriticalMinerals.ts
> +    const cmDischargeLicenceId = 'ee522a75-0873-4260-8f4f-85b2f387b543';
No specific reason. Will generate random.

2022-03-11 05:26 UTC, Farhad-Rezwan commented on app/Controllers/Http/CredentialsController.ts
> +    const assetEntry = await EntryLucidRepository.getAssetEntry(company.entries, request.input('event'));
I think parent ledger is for the asset. Looking into it.

2022-03-11 05:47 UTC, Farhad-Rezwan commented on app/Controllers/Http/CredentialsController.ts
> +    const assetEntry = await EntryLucidRepository.getAssetEntry(company.entries, request.input('event'));
Agree can use the parent asset ledger.

2022-03-15 02:18 UTC, smallbatch-apps requested changes

2022-03-15 02:18 UTC, smallbatch-apps commented on database/seeders/CriticalMinerals.ts
> +    await AssetLucidRepository.create(company, parentLedger, did, assetData);
This is being used statically

2022-03-15 06:20 UTC, Farhad-Rezwan commented on database/seeders/CriticalMinerals.ts
> +    await AssetLucidRepository.create(company, parentLedger, did, assetData);
The method is static, so we call it statically.

2022-03-16 04:10 UTC, merged